# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TuyaInc/TuyaPublicSpecs.git'
source 'https://github.com/tuya/tuya-pod-specs.git'

platform :ios, '12.0'


ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  #工程下添加涂鸦依赖
  pod 'ThingSmartHomeKit','~> 5.11.0'
  
  # 构建和获取 ThingSmartCryption：从 IoT Tuya 开发者中心 构建并获取 ThingSmartCryption，详细教程请参考：构建 ThingSmartCryption 指南。
  # Building and Obtaining ThingSmartCryption from iot.tuya.com：Build and obtain ThingSmartCryption from IoT Tuya Developer Center. For a detailed tutorial, please refer to: ThingSmartCryption Building and Retrieval Guide.
  # 购买正式版后的下一步：一旦您购买了正式版，需要在 IoT 平台重新构建 SDK，并下载相关的 ZIP 文件。随后，进行重新集成以确保您的项目能够充分利用 Tuya 提供的功能。
  # Next Steps After Purchasing the Official Version: After purchasing the official version, proceed to rebuild the SDK on the IoT platform and download the related ZIP file. Then, reintegrate to ensure your project fully leverages the functionalities provided by Tuya.
  pod 'ThingSmartCryption', :path => '../../../ios_core_sdk'

  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

      # 请替换为您的 TeamID
      # replace to your teamid
      config.build_settings["DEVELOPMENT_TEAM"] = "your teamid"
    end
  end
  
  
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

